use crate::constants::{SUMMARY_FILENAME, summary_path_for};
use crate::differ::DiffResult;
use crate::hasher;
use crate::scanner::DirNode;
use std::collections::BTreeMap;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::Command;
use std::sync::Mutex;
use std::time::{Duration, Instant};

const CHUNK_SIZE: usize = 5000;
const LLM_RATE_LIMIT: Duration = Duration::from_secs(1);

static LAST_LLM_CALL: Mutex<Option<Instant>> = Mutex::new(None);


const IGNORE_SECTION: &str = "<!--AI: Ignore the below section. It is used only for system tracking.-->";

/// Template for summary output.
/// Placeholders:
///   {comment}  — auto-generated warning comment
///   {title}    — directory path heading
///   {files}    — file summary bullet lines
///   {dirs}     — subdirectory summary sections
///   {hashes}   — SYSTEM-HASHES section
const SUMMARY_TEMPLATE: &str = "\
{comment}

# {title}
<!--AI: Index files are in the .archival/ directory mirroring the source tree. Look at {summary-file} files there before reading individual source files. If a file listed looks relevant, then read it. Otherwise skip it. -->

{files}

{dirs}

{ignore}
{hashes}
";

/// Generate or update index a dirty directory.
pub fn generate_summary(
    node: &DirNode,
    diff: &DiffResult,
    llm_cmd: &str,
    root: &Path,
    dry_run: bool,
    verbose: bool,
    chunk: bool,
) {
    let summary_path = summary_path_for(&node.path, root);
    let rel_path = node.path.strip_prefix(root).unwrap_or(&node.path);
    let title = if rel_path.as_os_str().is_empty() {
        root.file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string()
    } else {
        rel_path.to_string_lossy().to_string()
    };

    if dry_run {
        println!("Would regenerate: {}", summary_path.display());
        return;
    }

    if verbose {
        println!("Regenerating: {}", summary_path.display());
    }

    // Load existing summaries for reuse of unchanged items
    let (existing_file_summaries, existing_dir_summaries) =
        hasher::parse_existing_summaries(&summary_path);

    // Generate file summaries
    let file_summaries = generate_file_summaries(
        node,
        &diff.changed_files,
        &existing_file_summaries,
        llm_cmd,
        root,
        verbose,
        chunk,
    );

    // Generate subdir summaries
    let dir_summaries = generate_dir_summaries(
        node,
        &diff.changed_dirs,
        &existing_dir_summaries,
        llm_cmd,
        root,
        verbose,
    );

    // Build file lines
    let mut files_section = String::new();
    for file in &node.files {
        let name = file.path.file_name().unwrap_or_default().to_string_lossy();
        let rel = file.path.strip_prefix(root).unwrap_or(&file.path);
        if let Some(line) = file_summaries.get(name.as_ref()) {
            files_section.push_str(line);
        } else {
            files_section.push_str(&format!("- **{}**", rel.display()));
        }
        files_section.push('\n');
    }

    // Build dir sections
    let mut dirs_section = String::new();
    for subdir in &node.subdirs {
        let dir_name = subdir.file_name().unwrap_or_default().to_string_lossy();
        dirs_section.push_str(&format!("## {}/\n", dir_name));
        if let Some(summary) = dir_summaries.get(dir_name.as_ref()) {
            dirs_section.push_str(summary);
            dirs_section.push('\n');
        }
        dirs_section.push('\n');
    }

    // Build hash section
    let hashes_section = hasher::format_hash_section(&diff.current_hashes);

    // Inject into template
    let body = SUMMARY_TEMPLATE
        .replace("{comment}", "<!-- Do not edit below this line. This section is auto-generated by archival. -->")
        .replace("{title}", &title)
        .replace("{ignore}", IGNORE_SECTION)
        .replace("{files}\n", &files_section)
        .replace("{dirs}\n", &dirs_section)
        .replace("{hashes}\n", &hashes_section)
        .replace("{summary-file}", SUMMARY_FILENAME);

    if let Some(parent) = summary_path.parent() {
        fs::create_dir_all(parent).unwrap_or_else(|e| {
            eprintln!("warning: cannot create directory {}: {}", parent.display(), e);
        });
    }
    fs::write(&summary_path, &body).unwrap_or_else(|e| {
        eprintln!("warning: cannot write {}: {}", summary_path.display(), e);
    });
}

/// Generate summaries for files. Batches changed files into a single LLM call.
fn generate_file_summaries(
    node: &DirNode,
    changed_files: &[String],
    existing: &BTreeMap<String, String>,
    llm_cmd: &str,
    root: &Path,
    verbose: bool,
    chunk: bool,
) -> BTreeMap<String, String> {
    let mut result = BTreeMap::new();

    // Reuse unchanged file summaries
    for file in &node.files {
        let name = file
            .path
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();
        if !changed_files.contains(&name) {
            if let Some(existing_summary) = existing.get(&name) {
                result.insert(name, existing_summary.clone());
            }
        }
    }

    // Batch changed files
    if changed_files.is_empty() {
        return result;
    }

    // Collect files that need summarization, tracking relative paths for display
    let mut files_to_summarize: Vec<(&str, &Path, String)> = Vec::new(); // (basename, abs_path, rel_path)
    for file in &node.files {
        let name = file.path.file_name().unwrap_or_default().to_string_lossy();
        if changed_files.iter().any(|f| f == name.as_ref()) {
            let rel = file.path.strip_prefix(root).unwrap_or(&file.path)
                .to_string_lossy().to_string();
            files_to_summarize.push((
                Box::leak(name.into_owned().into_boxed_str()),
                &file.path,
                rel,
            ));
        }
    }

    // Build a map from basename to relative path for display
    let rel_paths: BTreeMap<String, String> = files_to_summarize
        .iter()
        .map(|(name, _, rel)| (name.to_string(), rel.clone()))
        .collect();

    // Handle large files (chunking) individually if enabled
    let mut batch_files: Vec<(String, String)> = Vec::new(); // (name, content)
    for (name, path, rel) in &files_to_summarize {
        let content = match fs::read_to_string(path) {
            Ok(c) => c,
            Err(_) => {
                // Try reading as bytes and converting lossy
                match fs::read(path) {
                    Ok(bytes) => String::from_utf8_lossy(&bytes).to_string(),
                    Err(e) => {
                        eprintln!("warning: cannot read {}: {}", path.display(), e);
                        continue;
                    }
                }
            }
        };

        if chunk && content.len() > CHUNK_SIZE {
            // Chunk and summarize individually
            if verbose {
                println!("  Chunking large file: {}", name);
            }
            let summary = summarize_large_file(path, &content, llm_cmd, verbose);
            result.insert(name.to_string(), format!("- **{}** — {}", rel, summary));
        } else {
            batch_files.push((name.to_string(), content));
        }
    }

    // Batch remaining files into a single LLM call
    if !batch_files.is_empty() {
        let batch_result = batch_summarize_files(&batch_files, llm_cmd, verbose);
        for (name, summary) in batch_result {
            let rel = rel_paths.get(&name).unwrap_or(&name);
            result.insert(name.clone(), format!("- **{}** — {}", rel, summary));
        }
    }

    result
}

/// Summarize a large file by chunking it.
fn summarize_large_file(_path: &Path, content: &str, llm_cmd: &str, verbose: bool) -> String {
    let chunks: Vec<&str> = content
        .as_bytes()
        .chunks(CHUNK_SIZE)
        .map(|chunk| {
            std::str::from_utf8(chunk).unwrap_or_else(|_| {
                let valid_len = chunk.iter().rposition(|&b| b < 0x80 || b >= 0xC0).unwrap_or(0);
                std::str::from_utf8(&chunk[..valid_len]).unwrap_or("")
            })
        })
        .collect();

    let mut chunk_summaries = Vec::new();
    for (i, chunk) in chunks.iter().enumerate() {
        if verbose {
            println!("    Summarizing chunk {}/{}", i + 1, chunks.len());
        }
        let prompt = format!(
            "Summarize this code chunk (part {}/{}) in one line:\n\n{}",
            i + 1,
            chunks.len(),
            chunk
        );
        match invoke_llm_with_stdin(llm_cmd, &prompt) {
            Ok(summary) => chunk_summaries.push(summary.trim().to_string()),
            Err(e) => {
                eprintln!("warning: LLM chunk summarization failed: {}", e);
                chunk_summaries.push(String::new());
            }
        }
    }

    // Stitch chunk summaries together
    let combined = chunk_summaries.join(" ");
    let stitch_prompt = format!(
        "Combine these chunk summaries into a single one-line summary:\n\n{}",
        combined
    );
    match invoke_llm_with_stdin(llm_cmd, &stitch_prompt) {
        Ok(s) => s.trim().to_string(),
        Err(_) => combined,
    }
}

/// Batch multiple files into a single LLM call, returning per-file summaries.
fn batch_summarize_files(
    files: &[(String, String)],
    llm_cmd: &str,
    verbose: bool,
) -> Vec<(String, String)> {
    if files.len() == 1 {
        let (name, _) = &files[0];
        if verbose {
            println!("  Summarizing: {}", name);
        }
        let prompt = format!(
            "Provide a one-line summary of this file named '{}':\n\n{}",
            name, files[0].1
        );
        return match invoke_llm_with_stdin(llm_cmd, &prompt) {
            Ok(summary) => vec![(name.clone(), summary.trim().to_string())],
            Err(e) => {
                eprintln!("warning: LLM failed for {}: {}", name, e);
                vec![(name.clone(), String::new())]
            }
        };
    }

    if verbose {
        println!("  Batch summarizing {} files", files.len());
    }

    // Build batch prompt with delimiters
    let mut prompt = String::from(
        "Provide a one-line summary for each of the following files. \
         Output each summary on its own line prefixed with the filename and a pipe character, \
         like: filename|summary\n\n",
    );
    for (name, content) in files {
        prompt.push_str(&format!("=== {} ===\n{}\n\n", name, content));
    }

    match invoke_llm_with_stdin(llm_cmd, &prompt) {
        Ok(output) => {
            let mut results = Vec::new();
            let lines: Vec<&str> = output.lines().collect();

            for (name, _) in files {
                let summary = lines
                    .iter()
                    .find_map(|line| {
                        if let Some(rest) = line.strip_prefix(&format!("{}|", name)) {
                            Some(rest.trim().to_string())
                        } else if let Some(rest) = line.strip_prefix(&format!("{} |", name)) {
                            Some(rest.trim().to_string())
                        } else {
                            None
                        }
                    })
                    .unwrap_or_default();
                results.push((name.clone(), summary));
            }
            results
        }
        Err(e) => {
            eprintln!("warning: batch LLM call failed: {}", e);
            files
                .iter()
                .map(|(name, _)| (name.clone(), String::new()))
                .collect()
        }
    }
}

/// Generate summaries for subdirectories.
fn generate_dir_summaries(
    node: &DirNode,
    changed_dirs: &[String],
    existing: &BTreeMap<String, String>,
    llm_cmd: &str,
    root: &Path,
    verbose: bool,
) -> BTreeMap<String, String> {
    let mut result = BTreeMap::new();

    for subdir in &node.subdirs {
        let dir_name = subdir
            .file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .to_string();

        if !changed_dirs.contains(&dir_name) {
            if let Some(existing_summary) = existing.get(&dir_name) {
                result.insert(dir_name, existing_summary.clone());
                continue;
            }
        }

        let sub_summary_path = summary_path_for(subdir, root);
        if !sub_summary_path.is_file() {
            continue;
        }

        if verbose {
            println!("  Summarizing subdir: {}/", dir_name);
        }

        // Read the index file content, stripping the ignore/hash sections
        let content = match fs::read_to_string(&sub_summary_path) {
            Ok(c) => hasher::strip_hash_section(&c).to_string(),
            Err(e) => {
                eprintln!("warning: cannot read {}: {}", sub_summary_path.display(), e);
                continue;
            }
        };

        let prompt = format!(
            "Below is a description of the contents of the '{}/' directory. \
             Summarize what this directory contains in 2-3 lines. \
             Do not describe the document itself, only summarize the actual content it describes.\n\n{}",
            dir_name, content
        );

        match invoke_llm_with_stdin(llm_cmd, &prompt) {
            Ok(summary) => {
                result.insert(dir_name, summary.trim().to_string());
            }
            Err(e) => {
                eprintln!(
                    "warning: LLM failed for {}: {}",
                    sub_summary_path.display(),
                    e
                );
                if let Some(existing_summary) = existing.get(&dir_name) {
                    result.insert(dir_name, existing_summary.clone());
                }
            }
        }
    }

    result
}

/// Invoke the LLM command with content passed via stdin.
/// Rate-limited to at most one call per second.
fn invoke_llm_with_stdin(llm_cmd: &str, input: &str) -> Result<String, String> {
    // Rate limit: wait until at least LLM_RATE_LIMIT has passed since last call
    {
        let mut last_call = LAST_LLM_CALL.lock().unwrap();
        if let Some(last) = *last_call {
            let elapsed = last.elapsed();
            if elapsed < LLM_RATE_LIMIT {
                std::thread::sleep(LLM_RATE_LIMIT - elapsed);
            }
        }
        *last_call = Some(Instant::now());
    }

    let parts: Vec<&str> = llm_cmd.split_whitespace().collect();
    if parts.is_empty() {
        return Err("empty llm_cmd".to_string());
    }

    let mut child = Command::new(parts[0])
        .args(&parts[1..])
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .map_err(|e| format!("failed to run '{}': {}", llm_cmd, e))?;

    if let Some(mut stdin) = child.stdin.take() {
        let _ = stdin.write_all(input.as_bytes());
    }

    let output = child
        .wait_with_output()
        .map_err(|e| format!("failed to wait for '{}': {}", llm_cmd, e))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(format!("llm_cmd exited with {}: {}", output.status, stderr));
    }

    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}
